[metadata]
  name = "Producer Kafka"
  version = "1.0.0"
  author = "Vagner Praia"
  email = "vagnerpraia@gmail.com"

[[constraint]]
  name = "github.com/segmentio/kafka-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/modern-go/concurrent"
  version = "1.0.3"

[[constraint]]
  name = "github.com/modern-go/reflect2"
  version = "1.0.1"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"